language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer update --no-interaction

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)